### PR TITLE
added a setting to minimize the main window to the icon tray

### LINKED ISSUE #207: Tray mode
Requested in discord by zaxaf: In this mode the tracker would be completely hidden except for a tray icon. We could also then offer docs on adding mtgatracker to auto start on boot, etc. Would need a way to dynamically spawn a tracker window, and hand off upload responsibility between the window & tray.

### PR DESCRIPTION
**Pull request by WizardRubic**
resolves #207 

I added a new setting to minimize the main window to the icon tray.

It only operates on the main window as I figured the other windows are kinda auxiliary and the user wouldn't normally minimize them and instead close them unless they needed to use the settings/history immediately. 

If the setting is switched off, the tracker does need to be restarted if the user wants the icon to disappear from the tray. This could probably be fixed by listening in on the settings changes but I'm not entirely sure it's necessary since the icon's usually end up in the hidden icons tray anyways. 

Also, on my machine multiple icons spawn when the app starts with the new setting on but quickly disappear. I'm not sure if it happens elsewhere as I can't see why it'd happen in the code. Wouldn't mind if someone could verify if that happens on their end!

Demo:
[https://youtu.be/C8ZOB6mJQ5I](https://youtu.be/C8ZOB6mJQ5I)

### CODE REVIEW

**Comment by shawkinsl** [comment]
Looks like this is pretty common: https://github.com/electron/electron/issues/7657

Anyways, I'll see if I can figure more out tomorrow or Sunday

**Comment by WizardRubic** [comment]
Well I'm kinda glad it crashed now instead of later :p 

It looks like there's a few ways to fix it I guess. The users in the link you posted suggested making a NativeImage, but I'm mildly concerned that if this error would have occurred, the NativeImage would be blank instead of crashing. Definitely isn't as bad as crashing I suppose and it's probably fixable if it happens.

I'll test later and see if I can dupe the error by deleting the image file.

**Comment by shawkinsl** [comment]
A few things I've read from that thread:
- `nativeImage`s only support png and jpg on _all_ platforms--ico may work on windows, but I suppose it should also be kept in one of those formats
- supposedly there can be issues if the image isn't exactly 16x16 px

**Comment by shawkinsl** [comment]
This branch worked for me: https://github.com/mtgatracker/mtgatracker/tree/user/shawkins/WizardRubic-tray

**Comment by WizardRubic** [comment]
Nice it appears to work for me too! 

I guess with the nativeImage even if the thing can't find the image it'll work:
[https://imgur.com/SgmYfjI.png](https://imgur.com/SgmYfjI.png)

I dunno if it's still a possibility but if it is, it doesn't crash and remains usable at least

**Comment by shawkinsl** [comment]
I can't update this branch, so I'm going to close this PR and open a new one (that contains this commit as well as the commits I added in user/shawkins/WizardRubic-tray

**Pull request closed without merging**
