### PR TITLE
Prototype for tracking draft history

### PR DESCRIPTION
**Pull request by isharacomix**
Prototype implementation of the draft-tracking feature request. #274 

During the draft, the state of the pick and pack zones at each step are stored. After the last card is chosen, the entire history is parsed and put into a compressed form in order to be sent to the inspector or whatever. Right now I just dump it into the logger, since I figure you might want to think over how you want to push to the inspector.

I wrote up an example of this format in a gist pulling from one of my test drafts: https://gist.github.com/isharacomix/86ad7c3308c698cd2986dc2ae30e2f00

During testing, I discovered that when the last card is chosen, `blob["draftPack"]` is actually `None`, which causes an exception to be thrown in the current code.

Feel free to use, ignore, or take apart for spare pieces. Roughly 3000 gems went into testing this. 💎

### CODE REVIEW

**Comment by shawkinsl** [comment]
Thanks a ton for starting this! I think we should probably report to inspector per pick instead of just keeping the history in memory, since it isn't guaranteed that players will start and finish a draft in the same play session (and MTGATracker might be restarted).

It's not immediately clear to me how we'll distinguish unique draft events within the log, since it looks like all draft events with the same format get the same "draftId" (`USERID:EVENTID:Draft`). Guess we'll just need some server side logic to check if the current blob has more cards than the previous blob

**Comment by isharacomix** [comment]
My thought process was prioritized around keeping incomplete data from hitting the inspector. If the tracker isn't running and a pick gets missed, you end up with a broken history anyway. But that's just my opinion.

If you wanted to send the complete pick and pack dictionaries with each pick (called `draft_history_event` in my code), you can identify a new draft starting whenever `history['picks'][n]` is not strictly a superset of `history['picks'][n-1]`. On each push to the API, check the most recently created draft object for the given `USERID:EVENTID:Draft`, then see if it makes sense to append it to that object or make a new one.

The advantage here would be if a user is being exceptionally silly and weaving between quick and competitive drafts for some reason.

**Comment by shawkinsl** [comment]
I'm not convinced we even need to care about "start of draft" or "end of draft" in the tracker. Let's just shove the pack and the pick to the API and handle it there. Here's what I built up tonight on the API:

```
POST /url/to/draft-pick:
body = {
  pick: <int:grpId>,
  pickNumber: <int:pickNumber>,
  pack: [<int:grpId>, <int:grpId>, ..], // this should contain pick, I think
  packNumber: <int:packNumber>,
  hero: <str:hero>,
  draftID: <str:draftID>
}
```

I like your idea that the API should decide on ingest if the pick belongs to the most recent draft, or if it's time to start a new one. (The logic is pretty simple: get the last pick in with this draftID and hero, compare its packNumber and pickNumber.)

Advantages:
- You can weave between draft modes, we'll sort it out in the API
- Quitting the tracker mid-draft doesn't lose a bunch of pickdata
- Starting a draft without the tracker only means you miss the picks you didn't pick with the tracker running, instead of the whole draft (we should be ok to show just the info we know about a draft, even if it's incomplete)

I'm going to work on some other stuff tonight, in case you want to pick this back up (if not, I'm also happy to come back to this sometime this week to make these changes)

**Comment by isharacomix** [comment]
Cool! I'll take a look and update it. If I have any questions, I'll ask in discord.

**Comment by isharacomix** [comment]
Changes pushed, peruse at your leisure.

**Comment by shawkinsl** [comment]
Looks great, thank you!

**Pull request merged**
