### PR TITLE
Rollup Setting Implented

### LINKED ISSUE #193: "roll-up" hide mode
Hide mode should be configurable in settings between the current "transparent" mode, and a new "roll up" mode. In "roll up" mode, the tracker should, like it says, "roll up," so that clicks can be sent behind the tracker. (jquery `slideUp` ?)

### PR DESCRIPTION
**Pull request by WizardRubic**
resolves #193

I added in a roll up setting! I don't know how to run the electron tests though so I wouldn't mind some help with that if it's necessary.

Thanks!

### CODE REVIEW

**Comment by shawkinsl** [comment]
On first glance, this looks.... incredible. Can't wait to test it out! Thanks, and happy #hacktoberfest!\

**Comment by shawkinsl** [comment]
There's one thing I would like to see different about this PR, and that's that I'd like _something_ to stick around when the tracker rolls up. For example, instead of disappearing, it would be perfect if at least the MTGATracker Title + zoom and setting buttons were still visible (forgive my lazy greenshotting, but a quick dirty example:)

image

I know that will probably require not-totally-insignificant HTML reorganization, so if you're not interested in fixing this, I'll merge this as-is by the end of the weekend and fix that before the next release. Again, this is really awesome and I'm kinda blown away that you hit all the pieces I would want (i.e. a toggle in settings that saves state across relaunches). Really great work here!

re: running electron tests.... this is embarrassing, but the extend of our electron tests is "Spencer plays around with it to see if anything broke." (Getting some kind of baseline tests to run against would also be a great hacktoberfest project!) Anyways, as far as that testing goes, this PR definitely passes!

**Comment by WizardRubic** [comment]
I think it's fixed for real now, it even zooms when minimized!
I restructed the index.html file so it now divides the container into tracker-header and tracker-body sections. Then I refactored resizeWindow() so it does its math on these 2 bodies instead of the whole container. 

Definitely don't mind review in case I missed something though :)

**Comment by shawkinsl** [comment]
This looks really great! (And gives me an excuse to put out an auto-update release with changes to reduce our network load as well).

I actually like this mode so much that I think I'm going to make it the default, and let users opt out.

**Comment by shawkinsl** [comment]
OK, there are still a few bugs that need to be ironed out (draft back button is missing, in game view rolls all the way up still), but I am going to merge this as-is and hack on it a little on my own while I'm working on some other things. Thanks again for doing this, this work is really solid!

**Pull request merged**
