### PR TITLE
Add minimize and close buttons

### PR DESCRIPTION
**Pull request by smkiewel**
Here's my first pass at minimize and close buttons. Let me know what you think. Not my best painting, I'll admit, but I think it works.

Fulfills #177

### CODE REVIEW

**Comment by shawkinsl** [comment]
I think the minimize and close buttons are excellent; they fit the theme of the hide button super well, and look really slick.

Unfortunately, I don't think all 5 (or 7?) buttons next to each other looks very good, though I admit I don't have a perfect solution. (for anyone following along at home, screenshot below)
image

I'm thinking maybe we keep hide, minimized, and close--these are buttons I image you'd always want fast access to--and stuff the others.... somewhere else; perhaps behind a drop down.... somewhere. (Maybe it's time to get keyboard shortcuts working and remove the zoom buttons altogether, with an option to bring them back, if you'd rather have functional and ugly)

Also, the hide button not having cursor: pointer was intentional. Some food for thought about buttons vs. links: https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

**Comment by smkiewel** [comment]
Heh - I added the cursor: pointer as an afterthought seeing it in diffs.

**Comment by smkiewel** [comment]
Also, I do think it looks cluttered, but couldn't find a better place for those other buttons.

I do think the second row can go off the main screen all the time. How to get them again, I'm not sure yet.

Like I said, first pass.

**Comment by shawkinsl** [comment]
Here's a quick mockup for my proposal:
image

image

**Comment by smkiewel** [comment]
Two possible suggestions:

menu-right
menu-left

I kinda really like left.

**Comment by shawkinsl** [comment]
Ooh, I like the left too. (Also, the hamburger icon is a good choice, 👍 )

**Comment by jnovack** [comment]
Love the hamburger, but really, how quickly do you need the application closed that you need two additional icons on the main window.

*THERE'S A FIRE IMMEDIATELY NEXT TO ME!  QUICK CLOSE THE APP!!!  NO TIME TO RIGHT-CLICK AND THEN CLICK CLOSE, I'LL BURN UP!!*

**Comment by smkiewel** [comment]
Sorry for my snark. I was really taken aback by the tone of your comment, but that doesn't excuse a similar response.

**Comment by shawkinsl** [comment]
Hey y'all, let's keep in mind that sarcasm doesn't translate well via keyboard, and try to be generally nice to each other.

Justin: this is a feature that's requested frequently. Understandable you don't want or need it, but many others do.

Shawn: I'm pretty sure Justin isn't attacking your work by questioning the premise; healthy skepticism can be useful in software dev, I'm sure he meant no harm.

**Comment by jnovack** [comment]
It's cool, I didn't take it as such.  There was no harm or attack meant, and no offense taken. :)

**Comment by smkiewel** [comment]
> To counter-point: How do people exit Magic The Gathering in full screen mode? How do they Concede when there's no button on the main screen?

Not by right-clicking, that's for sure.

**Comment by smkiewel** [comment]
Furthermore, how a full-screen paradigm inform UI decisions on a non-full screen program? Especially when there is a very strong established idiom for windowed programs, including Magic in windowed mode.

**Comment by jnovack** [comment]
It's been a real pleasure discussing this with you.

**Comment by smkiewel** [comment]
I hope you didn't find my comments off-putting. Just trying to express my perspective clearly.

**Comment by shawkinsl** [comment]
Proposal: how about we implement these buttons, and add a toggle in settings to hide them? This should make everyone happy, no?

**Comment by smkiewel** [comment]
> Proposal: how about we implement these buttons, and add a toggle in settings to hide them? This should make everyone happy, no?

I was just about to propose use of a custom theme that is uber minimal. Easy to hide buttons you dont want to see.

**Comment by shawkinsl** [comment]
@jnovack would you also find it useful to be able to hide the hide button? (that's a mouthful). I never use it, so I'd probably hide it myself (I prefer right-click hide, left-click show), but I've chosen to leave it there so far for everyone else who does.

**Comment by shawkinsl** [comment]
@smkiewel I don't think a theme would be a terrible solution, _but_ I admit that theme support is lacking right now. (for example, right now if you use a .exe installer to update instead of letting the auto-updater do its thing, your theme folder gets wiped out.) I'm a little hesitant to offer any permanent solution to an issue a user has that's "use a theme" before at least that issue is resolved. (I think we just need to use a different directory to store themes in, in fact I'll file that ticket right now.)

**Comment by smkiewel** [comment]
Replaced by #416

**Comment by shawkinsl** [comment]
Huge fan of how this is coming along, looks very nice! The buttons aren't working for me though :( have you tested this outside of debug mode at all? (or are they still just WIP?)
buttons_not_working

**Comment by shawkinsl** [comment]
oh, oops, just saw the comment above. ignore me 🙃

**Pull request closed without merging**
